---
title: "R Notebook"
output: html_notebook
---
```{r echo=FALSE, warning=FALSE}
library(readxl)
library(survival)
library(survminer)
```

# Part A

```{r}
std <- read_xlsx('data/std_2019_pw.xlsx')

kmp<-survfit(Surv(std$time,std$cens)~std$type,type="kaplan-meier")

ggsurv <- ggsurvplot(kmp , data = std, xlab="Days to re-infection",
                     ylab="Survival estimate",
                     legend.labs = c("Gonorrhea", "Chlamydia","Both"), linetype = 'strata') + 
  labs(title    = "Survival estimates for time to re-infection",
       subtitle = "Based on Kaplan-Meier estimates")

ggsurv <- ggpar(ggsurv, font.title    = c(14, "bold"),
                font.subtitle = c(12, "bold.italic"),        
                font.x        = c(11, "plain"),          
                font.y        = c(11, "plain"))

print(ggsurv)
```

From Figure 1 we can see that Chlamydia has an overall higher survival rate in terms of re-infection than does Gonorrhea.  A person who has been infected with both appears to lie in between the the singular infection, perhaps being pulled up by the higher survival rate of Chlamydia